name: Generate Commit Word Cloud

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:
    inputs:
      color_scheme:
        description: 'Color scheme to use'
        required: false
        default: 'github'
        type: choice
        options:
          - github
          - neon
          - pastel
          - sunset
          - ocean

jobs:
  generate-wordcloud:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wordcloud pandas numpy pillow matplotlib
          pip install -e .
      
      - name: Generate word cloud
        id: wordcloud
        run: |
          python - << EOF
          from wordcloud_generator.visualizer import CommitWordCloudGenerator
          import subprocess
          import json
          
          # Get commit messages
          git_log = subprocess.check_output(
              ['git', 'log', '--pretty=format:%s'],
              encoding='utf-8'
          ).lower()
          
          # Generate word cloud
          generator = CommitWordCloudGenerator()
          generator.color_scheme = "${{ github.event.inputs.color_scheme || 'github' }}"
          
          svg_path, metadata = generator.generate(git_log)
          
          # Save metadata for README
          with open('wordcloud_metadata.json', 'w') as f:
              json.dump(metadata, f, indent=2)
          EOF
      
      - name: Update README
        run: |
          # Create temporary file for the new content
          cat > wordcloud_section.md << 'EOL'
          ## Commit Word Cloud
          
          ![Commit Word Cloud](commit_wordcloud.svg)
          
          <details>
          <summary>Word Cloud Statistics</summary>
          
          ```json
          $(cat wordcloud_metadata.json | jq -r '.')
          ```
          </details>
          
          <!-- wordcloud-end -->
          EOL
          
          # Update or create README
          if [ -f README.md ]; then
            # Remove existing section if present and add new section
            sed -i '/## Commit Word Cloud/,/<!-- wordcloud-end -->/d' README.md
            cat wordcloud_section.md >> README.md
          else
            # Create new README
            cat wordcloud_section.md > README.md
          fi
          
          # Clean up temporary file
          rm wordcloud_section.md

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add commit_wordcloud.svg README.md
          git commit -m "docs: update commit word cloud visualization [skip ci]" || exit 0
          git push
